language: python
python:
    - "2.7"
addons:
    postgresql: "9.4"
sudo: false
install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install .
    - travis_retry pip install invoke==0.13.0
    - inv setup_tests
script:
    - inv test
