language: python
python:
    - "2.7"
addons:
    postgresql: "9.4"
sudo: false
install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install . --process-dependency-links
    - travis_retry pip install -r dev-requirements.txt
    - inv setup_tests
script:
    - inv test
